openai_chain_agent:
  agent_id: openai_chain_agent
  name: open_ai_gpt35
  description: openai based agent with simple prompt 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-3.5-turbo
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

openai_tool_chain:
  agent_id: openai_tool_chain
  name: open_ai_gpt35
  description: openai based agent with prompt coming from langchain hub  and tool
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: gpt-3.5-turbo
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: openai-functions-agent
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily

openai_graph_agent:
  agent_id: openai_graph_agent
  name: "Base Graph Agent using openAI"
  description: openai based agent using graph and simple prompt 
  runner_class_name: athena.llm.agents.base_graph_agent.BaseGraphAgent
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-3.5-turbo
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

base_tool_graph_agent:
  agent_id: base_tool_graph_agent
  name: "Base Graph Agent using tools"
  runner_class_name: athena.llm.agents.base_tool_graph_agent.BaseToolGraphAgent
  modelClassName: langchain_openai.ChatOpenAI
  description: A default agent that uses LLM and search tool to do web search
  modelName: gpt-3.5-turbo
  prompt_ref: openai-functions-agent
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily

anthropic_claude_3_base:
  agent_id: anthropic_claude_3_base
  name: claude-3-opus
  description: Anthropic Claude 3 based agent with simple prompt 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelClassName: langchain_anthropic.ChatAnthropic
  modelName: claude-3-opus-20240229
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

ollama_mistral:
  agent_id: ollama_mistral
  name: "ollama mistral"
  description: Mistral model running locally with Ollama
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: mistral
  modelClassName: langchain_community.chat_models.ChatOllama
  prompt_ref: mistral_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1

mistral_large_agent:
  agent_id: mistral_large_agent
  name: "mistral_large_agent"
  description: Mistral large model via Mistral API 
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  modelName: mistral
  modelClassName: langchain_mistralai.chat_models.ChatMistralAI
  prompt_ref: mistral_rag_prompt
  temperature: 0
  top_k: 1
  top_p: 1

fake_agent:
  agent_id: fake_agent
  name: fake_agent
  description: Fake agent for testing 
  runner_class_name: athena.llm.agents.fake_agent.FakeAgent
  modelName: not_needed
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1


mistral_large:
  agent_id: mistral_large
  runner_class_name: athena.llm.agents.agent_mgr.OwlAgentAbstractRunner
  description:  A Mistral large agent for RAG question and answer
  modelClassName: langchain_mistralai.chat_models.ChatMistralAI
  modelName: mistral-large-latest
  name: Mistral based agent
  prompt_ref: mistral_rag_prompt
  temperature: 0
  top_k: 1
  tools: []


