open_ai:
  agent_id: 8bbf0c11-192a-450a-8959-779fe67e2563
  class_name: athena.llm.agents.agent_openai.OpenAIClient
  model_name: gpt-3.5-turbo-0125
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

