site_name: Athena Decision Systems Product Documentation
copyright: Copyright &copy; 2024 Athena Decision Systems
repo_url: https://github.com/AthenaDecisionSystems/athena-owl-core
nav:
  - Introduction: index.md
  - Architecture: 
    - Introduction: arch.md
    - OwlAgent design: design.md
  - Demos: 
    - Introduction: demos/index.md
    - Environment Setup: tutorials/dev_env.md
    - IBU Insurance: demos/insurance.md
    - IBM-ODM LoanApp: demos/miniloan.md
  - Gen AI to Hybrid AI: gen_ai_gs.md
  - Tutorials:
    - Building New Mistral Agent: tutorials/new_mistral_agent.md
    - Build Your Own Solution: demos/build_sol.md

theme: 
  name: material
  logo: assets/owl.png
  favicon: assets/owl.png
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.code.copy
      - content.tooltips
      - search.highlight
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      # - navigation.sections
      #- navigation.expand
      - navigation.top
      - navigation.footer
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "75%"
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/AthenaDecisionSystems'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/company/athena-decision-systems/'
