apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-cm
data:
  config.yaml: |
    logging_level: DEBUG
    version: v0.0.6
    owl_env_path: /app/.env
    app_index_path: /app/athena/routers/index.html
    owl_glossary_path: /app/athena/config/glossary.json
    owl_agents_path: /app/athena/config/agents.yaml
    owl_tools_path: /app/athena/config/tools.yaml
    owl_prompts_path: /app/athena/config/prompts.yaml
    owl_agent_content_collection_name: base_collection
    owl_agent_default_agent: openai_chain_agent
    owl_agent_content_file_path: /app/file_content
    owl_agent_vs_path: /app/chromadb
    owl_agent_vs_embedding_fct: OpenAIEmbeddings
    owl_agent_llm_history_length: 5
    owl_agent_tool_factory_class:  athena.llm.tools.tool_mgr.DefaultToolInstanceFactory
    owl_agent_decision_service_fct_name: athena.itg.decisions.nba_ds_dummy.callDecisionService

