openai_chain:
  agent_id: openai_chain
  name: open_ai_gpt35
  description: openai based agent with simple prompt 
  #class_name: athena.llm.agents.agent_openai.OpenAIAgent
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  modelClassName: langchain_openai.ChatOpenAI
  modelName: gpt-3.5-turbo-0125
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

openai_tool_chain:
  agent_id: openai_tool_chain
  name: open_ai_gpt35
  description: openai based agent with prompt coming from langchain hub  and tool
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  modelName: gpt-3.5-turbo-0125
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: hwchase17/openai-functions-agent
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily


mistral_large:
  agent_id: mistral_large
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  description:  A Mistral large agent for RAG question and answer
  modelClassName: langchain_mistralai.chat_models.ChatMistralAI
  modelName: mistral-large-latest
  name: Mistral based agent
  prompt_ref: mistral_rag_prompt
  temperature: 0
  top_k: 1
  tools: []


