# Copyright 2024 Athena Decision Systems
# @author Jerome Boyer
# IBU Loan Application Demo
# ------------------------------------------------------------------
logging_level: DEBUG
version: 0.0.2
owl_env_path: /app/.env
# DEPRECATED
owl_agent_llm_client_class: athena.llm.agent_openai.OpenAIClient
owl_agent_llm_model: gpt-3.5-turbo-0125


#for loan validation demo
#app_loanapp_decision_service_url: http://decisionsvc:9060/DecisionService/rest/v1/production_deployment/1.0/loan_validation_production
app_loanapp_decision_service_url: http://decisionsvc:9060/DecisionService/rest/v1/mydeployment/1.0/Miniloan_ServiceRuleset/1.0
owl_glossary_path: /app/config/glossary.json

owl_assistants_path: /app/config/assistants.yaml
owl_agents_path: /app/config/agents.yaml
owl_tools_path: /app/config/tools.yaml
owl_prompts_path: /app/config/prompts.json
owl_prompts_key_name: defaut_prompt
owl_agent_content_vstore_url: http://localhost:8005
owl_agent_content_collection_name: ibu_loan
owl_agent_content_file_path: /app/file_content
owl_agent_vs_path: /app/chromadb
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_llm_history_length: 5
owl_agent_decision_service_fct_name: ibu.itg.decisions.next_best_action_ds_client.callDecisionService

owl_agent_tool_factory_class:  ibu.llm.tools.client_tools.IbuLoanToolInstanceFactory
app_borrower_repository: ibu.itg.ds.loanapp_borrower_repo_mock.BorrowerRepositoryInMem
