default_prompt:
    name:  Default prompt
    prompt_id: default_prompt
    locales:
    - locale: en
      text: "Answer the user's question based on the conversation history: {chat_history} \n\n question: {input}"
    - locale: fr
      text: "Repond aux questions de l'utilisateur en prenant en compte le historique de la conversation: \n\n{chat_history}  \n\n et la question: {input}"
    - locale: es
      text: "Responda las preguntas del usuario según el historial de conversaciones  {chat_history} \n\n question: {input}"
    
mistral_rag_prompt:
    name: Mistral Bank Query Classification
    prompt_id: mistral_rag_prompt
    locales:
    - locale: en
      text: |
        "Answer the following question based only on the provided context:

        <context>
        {context}
        </context>

        Question: {input}"
