# used to run the core backend in dev mode with the start_backend.sh script
version: dev-0.0.1
logging_level: DEBUG
logging_level_int: 10

app_index_path: ./athena/routers/index.html
owl_prompts_key_name: default_prompt
owl_agents_path: ./athena/config/agents.yaml
owl_tools_path: ./athena/config/tools.yaml
owl_prompts_path: ../tests/ut/config/prompts.yaml
owl_glossary_path: ./athena/config/glossary.json

owl_agent_llm_history_length: 5
owl_agent_content_collection_name: base_collection
owl_agent_content_file_path: ../tests/ut/file_content
owl_agent_vs_path: ../tests/ut/chromadb
owl_agent_vs_embedding_fct: OpenAIEmbeddings