logging_level: DEBUG
version: v0.0.2
owl_env_path: ../.env
owl_agent_decision_service_fct_name: athena.itg.decisions.nba_ds_dummy.callDecisionService
owl_glossary_path: ./athena/config/glossary.json
owl_prompts_path: ./athena/config/prompts.json
owl_assistants_path: ./athena/config/assistants.yaml
owl_agents_path: ./athena/config/agents.yaml
owl_tools_path: ./athena/config/tools.yaml
owl_prompts_key_name: default_prompt
#owl_agent_content_vstore_url: http://localhost:8005
owl_agent_content_collection_name: base_collection
owl_agent_content_file_path: ./file_content
owl_agent_vs_path: ./chromadb
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_llm_history_length: 5

owl_agent_llm_client_class: athena.llm.agent_openai.OpenAIClient
owl_agent_llm_model: gpt-3.5-turbo-0125