apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: decisionsvc
  name: decisionsvc
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9443
    - name: "9060"
      port: 9060
      targetPort: 9060
  selector:
    io.kompose.service: decisionsvc
