apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: decisionsvc
  name: decisionsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decisionsvc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: decisionsvc
    spec:
      containers:
        - env:
            - name: LICENSE
              value: accept
            - name: SAMPLE
              value: "true"
          image: icr.io/cpopen/odm-k8s/odm:8.12
          name: decisionsvc
          ports:
            - containerPort: 9443
              protocol: TCP
            - containerPort: 9060
              protocol: TCP
          volumeMounts:
            - mountPath: /config/dbdata
              name: decisionsvc-claim0
      hostname: decisionsvc
      restartPolicy: Always
      volumes:
        - name: decisionsvc-claim0
          persistentVolumeClaim:
            claimName: decisionsvc-claim0
