services:
  owl-backend:
    hostname: owl-backend
    image: localhost:5002/athena-owl-backend:1.0.0
    container_name: owl-backend
    build:
      context: ../../owl-agent-backend/src
    ports:
      - 8000:8000
    environment:
      CONFIG_FILE: /app/config/config.yaml
      #OPENAI_API_KEY: $OPENAI_API_KEY
    env_file:
      - .env
 
  owl-frontend:
    hostname: owl-frontend
    image: localhost:5002/athena-owl-frontend:1.0.0
    container_name: owl-frontend
    build:
      context: ../../owl-agent-interface/
    ports:
      - 3000:3000
    environment:
      - REACT_APP_OWL_AGENT_NAME="IBU Insurance Management Agent"
      - NEXT_PUBLIC_BACKEND_BASE_API=http://localhost:8000/api/v1/
      - REACT_APP_DEMO_TEXT="My name is Sonya Smith, I have problem with my claim 2 for my water damage, my carpet is expensive, I m surprise of the current coverage, very disappointing?"
  decisionsvc:
    image: icr.io/cpopen/odm-k8s/odm:8.12
    hostname: decisionsvc
    container_name: decisionsvc
    user: "1001:0"
    ports:
      - 9443:9443
      - 9060:9060
    environment:
      - SAMPLE=true
      - LICENSE=accept
    volumes:
      - ./resdb:/config/dbdata/
