services:
  owl-backend:
    hostname: owl-backend
    image: athenadecisionsystems/athena-owl-backend:1.0.0
    pull_policy: always
    container_name: owl-backend
    build:
      context: ../../owl-agent-backend/src
    ports:
      - 8000:8000
    environment:
      CONFIG_FILE: /app/config/config.yaml
      #OPENAI_API_KEY: $OPENAI_API_KEY
    env_file:
      - .env
    volumes:
      - ./data/file_content:/app/file_content
      - ./data/vs_db:/app/vs_db
 
  owl-frontend:
    hostname: owl-frontend
    image: athenadecisionsystems/athena-owl-frontend:1.0.0
    pull_policy: always
    container_name: owl-frontend
    build:
      context: ../../owl-agent-interface/
    ports:
      - 3000:3000
    environment:
      - REACT_APP_OWL_AGENT_NAME="IBU Insurance Management Agent"
      - NEXT_PUBLIC_BACKEND_BASE_API=http://localhost:8000/api/v1/
      - REACT_APP_DEMO_TEXT="My name is Sonya Smith, I have problem with my claim 2 for my water damage, my carpet is expensive, I m surprise of the current coverage, very disappointing?"
  decisionsvc:
    image: icr.io/cpopen/odm-k8s/odm:8.12
    hostname: decisionsvc
    container_name: decisionsvc
    user: "1001:0"
    ports:
      - 9443:9443
      - 9060:9060
    environment:
      - SAMPLE=true
      - LICENSE=accept
    volumes:
      - ./resdb:/config/dbdata/
  keycloak_web:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080

  keycloakdb:
    image: postgres
    hostname: keycloakdb
    container_name: keycloakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: