apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: owl-backend
  name: owl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: owl-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: owl-backend
    spec:
      containers:
        - env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: ANTHROPIC_API_KEY
                  name: env
            - name: COHERE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: COHERE_API_KEY
                  name: env
            - name: CONFIG_FILE
              value: /app/config/config.yaml
            - name: GOOGLE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_API_KEY
                  name: env
            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: HUGGINGFACEHUB_API_TOKEN
                  name: env
            - name: IBM_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: IBM_API_KEY
                  name: env
            - name: IBM_WATSON_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  key: IBM_WATSON_PROJECT_ID
                  name: env
            - name: LANGCHAIN_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_API_KEY
                  name: env
            - name: LANGCHAIN_TRACING_V2
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_TRACING_V2
                  name: env
            - name: MISTRAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MISTRAL_API_KEY
                  name: env
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: env
            - name: SERPER_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: SERPER_API_KEY
                  name: env
            - name: TAVILY_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TAVILY_API_KEY
                  name: env
            - name: WATSONX_APIKEY
              valueFrom:
                configMapKeyRef:
                  key: WATSONX_APIKEY
                  name: env
          image: localhost:5002/athena-owl-backend:1.0.0
          name: owl-backend
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: owl-backend-claim0
            - mountPath: /app/.env
              name: owl-backend-claim1
            - mountPath: /app/file_content
              name: owl-backend-claim2
            - mountPath: /app/chromadb
              name: owl-backend-claim3
            - mountPath: /app/ibu
              name: owl-backend-claim4
      hostname: owl-backend
      restartPolicy: Always
      volumes:
        - name: owl-backend-claim0
          persistentVolumeClaim:
            claimName: owl-backend-claim0
        - name: owl-backend-claim1
          persistentVolumeClaim:
            claimName: owl-backend-claim1
        - name: owl-backend-claim2
          persistentVolumeClaim:
            claimName: owl-backend-claim2
        - name: owl-backend-claim3
          persistentVolumeClaim:
            claimName: owl-backend-claim3
        - name: owl-backend-claim4
          persistentVolumeClaim:
            claimName: owl-backend-claim4
