apiVersion: v1
kind: Pod
metadata:
  name: "owl-backend-test-connection"
  labels:
    helm.sh/chart: owl-backend-0.1.0
    app.kubernetes.io/name: owl-backend
    app.kubernetes.io/instance: owl-backend
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['owl-backend:8000']
  restartPolicy: Never